name: Build and Release with Docker

on:
  schedule:
    - cron: '12 */2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-changes:
    runs-on: ubuntu-latest
    container:
      image: docker.io/oven/bun:latest
    outputs:
      has_changes: ${{ steps.check.outputs.has_changes }}
    steps:
      - name: Check release version exists
        id: check
        run: |
          version=$(bun -v)

          if gh release view "${version}"; then
            echo "Release ${version} already exists. Skipping build."
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Release ${version} does not exist. Proceeding with build."
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  amd64-glibc:
    needs: check-changes
    if: needs.check-changes.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    container:
      image: docker.io/oven/bun:latest
    outputs:
      AMD64_GLIBC_BUN_VERSION: ${{ steps.get-version.outputs.AMD64_GLIBC_BUN_VERSION }}
      AMD64_GLIBC_INDEX_DIGEST: ${{ steps.get-digest.outputs.AMD64_GLIBC_INDEX_DIGEST }}
      AMD64_GLIBC_MANIFEST_DIGEST: ${{ steps.get-digest.outputs.AMD64_GLIBC_MANIFEST_DIGEST }}

    steps:
      - name: Install curl
        run: |
          apt-get update
          apt-get install -y curl ca-certificates jq

      - name: Checkout Digest
        id: get-digest
        run: |
          owner=oven
          repo=bun
          tag=latest

          output=$(mktemp)

          curl -s -o ${output} "https://hub.docker.com/v2/namespaces/${owner}/repositories/${repo}/tags/${tag}"

          echo "AMD64_GLIBC_INDEX_DIGEST=$(jq -r .digest ${output})"
          echo "AMD64_GLIBC_MANIFEST_DIGEST=$(jq -r 'first(.images.[] | select(.architecture == "amd64")) | .digest' ${output})"
          echo "AMD64_GLIBC_INDEX_DIGEST=$(jq -r .digest ${output})" >> $GITHUB_OUTPUT
          echo "AMD64_GLIBC_MANIFEST_DIGEST=$(jq -r 'first(.images.[] | select(.architecture == "amd64")) | .digest' ${output})" >> $GITHUB_OUTPUT

      - name: Compile project
        id: get-version
        run: |
          version=$(bun -v)
          echo "BUN_VERSION=${version}" >> $GITHUB_ENV
          echo "AMD64_GLIBC_BUN_VERSION=${version}" >> $GITHUB_OUTPUT

          mkdir /app
          cd /app
          echo 'console.log("Hello via Bun!");' > ./index.ts
          bun build ./index.ts --compile
          mv ./index ./bun-${version}-compiled-amd64-glibc

          sha256sum ./bun-${version}-compiled-amd64-glibc

      - name: Upload Artifact amd64-glibc
        uses: actions/upload-artifact@v4
        with:
          name: bun-${{ env.BUN_VERSION }}-compiled-amd64-glibc
          path: /app/bun-${{ env.BUN_VERSION }}-compiled-amd64-glibc

  amd64-musl:
    needs: check-changes
    if: needs.check-changes.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    container:
      image: docker.io/oven/bun:alpine
    outputs:
      AMD64_MUSL_BUN_VERSION: ${{ steps.get-version.outputs.AMD64_MUSL_BUN_VERSION }}
      AMD64_MUSL_INDEX_DIGEST: ${{ steps.get-digest.outputs.AMD64_MUSL_INDEX_DIGEST }}
      AMD64_MUSL_MANIFEST_DIGEST: ${{ steps.get-digest.outputs.AMD64_MUSL_MANIFEST_DIGEST }}

    steps:
      - name: Install curl
        run: apk add --no-cache curl ca-certificates jq

      - name: Checkout Digest
        id: get-digest
        run: |
          owner=oven
          repo=bun
          tag=alpine

          output=$(mktemp)

          curl -s -o ${output} "https://hub.docker.com/v2/namespaces/${owner}/repositories/${repo}/tags/${tag}"

          echo "AMD64_MUSL_INDEX_DIGEST=$(jq -r .digest ${output})"
          echo "AMD64_MUSL_MANIFEST_DIGEST=$(jq -r 'first(.images.[] | select(.architecture == "amd64")) | .digest' ${output})"
          echo "AMD64_MUSL_INDEX_DIGEST=$(jq -r .digest ${output})" >> $GITHUB_OUTPUT
          echo "AMD64_MUSL_MANIFEST_DIGEST=$(jq -r 'first(.images.[] | select(.architecture == "amd64")) | .digest' ${output})" >> $GITHUB_OUTPUT

      - name: Compile project
        id: get-version
        run: |
          version=$(bun -v)
          echo BUN_VERSION=${version} >> $GITHUB_ENV
          echo "AMD64_MUSL_BUN_VERSION=${version}" >> $GITHUB_OUTPUT

          mkdir /app
          cd /app
          echo 'console.log("Hello via Bun!");' > ./index.ts
          bun build ./index.ts --compile
          mv ./index ./bun-${version}-compiled-amd64-musl

          sha256sum ./bun-${version}-compiled-amd64-musl

      - name: Upload Artifact amd64-musl
        uses: actions/upload-artifact@v4
        with:
          name: bun-${{ env.BUN_VERSION }}-compiled-amd64-musl
          path: /app/bun-${{ env.BUN_VERSION }}-compiled-amd64-musl

  publish-release:
    runs-on: ubuntu-latest
    needs: [check-changes, amd64-glibc, amd64-musl]
    if: needs.check-changes.outputs.has_changes == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.amd64-glibc.outputs.AMD64_GLIBC_BUN_VERSION }}
          files: dist/*
          body: |
            # bun-${{ needs.amd64-glibc.outputs.AMD64_GLIBC_BUN_VERSION }}-compiled-amd64-glibc
            Amd64-glibc Index Digest: ${{ needs.amd64-glibc.outputs.AMD64_GLIBC_INDEX_DIGEST }}
            Amd64-glibc Manifest Digest: ${{ needs.amd64-glibc.outputs.AMD64_GLIBC_MANIFEST_DIGEST }}

            # bun-${{ needs.amd64-musl.outputs.AMD64_MUSL_BUN_VERSION }}-compiled-amd64-musl
            Amd64-musl Index Digest: ${{ needs.amd64-musl.outputs.AMD64_MUSL_INDEX_DIGEST }}
            Amd64-musl Manifest Digest: ${{ needs.amd64-musl.outputs.AMD64_MUSL_MANIFEST_DIGEST }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
